name: __projectname__
author: Damon Douglas <douglas.damon@gmail.com>
homepage: __homepage__
version: 0.1.0
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  polymer: '^1.0.0-rc.15'
  web_components: '^0.12.2'
  polymer_elements: '^1.0.0-rc.8'
  browser: '>=0.10.0+2 <0.11.0'
  
dev_dependencies:
  test: '>=0.12.13+1 <0.13.0'

transformers:
- polymer:
    entry_points:
    - web/index.html
